version: "3"
services:
  node:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    - /app/node_modules
    links:
    - pg 

  pg:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
